n=str(input("primul cuvant:"))
m=str(input("al doilea cuvant:"))
x=str(input("al treilea cuvant:"))
y=str(input("al patrumea cuvant:"))
print(n)
print(m)
print(x)
print(y)
print(n+" "+m+" "+x+" "+y+".")